### ISSUE TITLE
feat(xtk): Add XTK as a new framework

### ISSUE THREAD

**Issue by gaiborjosue** [mpsych/boostlet#6]
Hello, 

This issue is to create a thread in order to document the progress on xtk and its addition to boostlet as a framework. 

As it is right now, XTK works for 2D images. The tools that can be used for xtk in boostlet right now are the Sobel filter and plotly.

We are currently working on SegmentAnything integration. 

The up-to-date progress is on my Github Pages: https://gaiborjosue.github.io/boostlet/

And you can test it on the xtk demo: https://gaiborjosue.github.io/API_Images/xtk.html or to access the same link I updated the UI, so you can also click on the example websites.

**Comment by gaiborjosue** [comment]
Hello @shrutivarade as mentioned, the only feature left for 2d is the box and set_mask for xtk. We talked about using the new widgets you created, which is an excellent idea. We should start with that 👍

**Comment by shrutivarade** [comment]
Hello @gaiborjosue, I have integrated the Widget library BoxCraft.js with Boostlet's Segmentanything and it is working for Niivue but having an issue with OpenSeaDragon.js, as it is creating multiple on the overlay canvas. I am looking into it.

**Comment by gaiborjosue** [comment]
Hello @shrutivarade, any news on the box widget?
